version: '3'

services:
  monitor:
    build: ./monitor
    image: cywang117/balena-update-monitor
    container_name: update-monitor
    restart: on-failure
    # Device UUID and balenaCloud APIKEY variables need to be specified when running image
    # docker-compose up, or docker run --rm --name update-monitor --env-file ./.env cywang117/balena-update-monitor